---
- hosts: localhost
  tasks:
    - name: Return motd to registered var
      ansible.builtin.command: cat /home/ec2-user/file2
      register: mymotd
    
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: mymotd
        verbosity: 2
    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg:
        - "Provisioning based on YOUR_KEY which is: {{ mymotd.stdout }}"
    - name: Get pretty release date
      ansible.builtin.command: date '+%Y-%m-%d %H:%M:%S'
      register: release_date
    - name: Print current timestamp
      ansible.builtin.debug:
        msg:
        - "{{ release_date.stdout }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/some_directory
        state: directory
        mode: '0755'
