---
- hosts: localhost
  tasks:
    - name: Return motd to registered var
      ansible.builtin.command: cat /etc/motd
      register: mymotd
    
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: mymotd
        verbosity: 2
    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg:
        - "Provisioning based on YOUR_KEY which is: {{ motd }}"
