---
- hosts: localhost
  tasks:
    - name: Return motd to registered var
      ansible.builtin.command: cat /etc/motd
      register: mymotd
    
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: mymotd
        verbosity: 2
