---
- hosts: localhost
  tasks:
    - name: Return motd to registered var
      ansible.builtin.command: cat /etc/motd
      register: mymotd
    - name: Return motd to registered var
      ansible.builtin.command: cat /etc/motd
      register: mymotd
